### PR TITLE
DEV-667: get it working so we can stage an item

### PR DESCRIPTION
**Pull request by aelkiss**

### CODE REVIEW

**Comment by aelkiss** [comment]
We should probably also rename `master` to `main` while we're in here.

**Comment by aelkiss** [comment]
The underlying `rpairtree` gem was not compatible with ruby 3.2 (it relied on the deprecated `File.exists?`). I got ownership on the original https://github.com/ruby-microservices/pairtree and gem; once we get https://github.com/ruby-microservices/pairtree/pull/5 merged I'll release a new version of the gem and update this to use that.

**Comment by aelkiss** [comment]
I will update this to use the new upstream pairtree gem but @billdueber if you have a chance to look at this I'd appreciate it, or @moseshll  if you have time

**Comment by billdueber** [comment]
Is this one ready to go now? Code is all clean and obvious, and I'm happy to merge if you think you're done with the whole upstream song-and-dance.

**Comment by aelkiss** [comment]
Yes, this is ready to go. I'm not sure why the checks aren't showing up as completed, but it looks like they passed?? I'll go ahead and merge imminently.

**Comment by aelkiss** [comment]
According to https://www.githubstatus.com/ github actions is having some issue. I ran the matrixed tests locally with https://github.com/nektos/act and all 4 passed, so I'm going to go ahead and merge.

**Pull request merged**
